### PR TITLE
Add transform for .get()

### PR DESCRIPTION
**Pull request by nlfurniss**
As discusses, this transform is fine since it returns an HTMLElement instead of a jQuery element like `first()/last()` does

### CODE REVIEW

**Comment by nlfurniss** [comment]
@simonihmig any concerns with this one?

**Comment by simonihmig** [comment]
@nlfurniss no, just forgot about it, sorry! Thanks again!

**Comment by nlfurniss** [comment]
Mind cutting a new version? I have a bunch of file with `.get(x)` :-P

**Comment by simonihmig** [comment]
@nlfurniss done!

**Pull request merged**
